# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-08 13:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 8, 13, 12, 5, 211610, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
