# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-09 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20170609_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_chapter',
            old_name='chapter',
            new_name='name',
        ),
    ]
