# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-11 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20170611_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='\u9605\u8bfb\u91cf'),
        ),
    ]
