# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-11 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_book_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='excerpt',
            field=models.CharField(blank=True, max_length=200, verbose_name='\u6458\u8981'),
        ),
    ]
