# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-12 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_book_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created_time',
            field=models.DateTimeField(null=True, verbose_name='\u65f6\u95f4'),
        ),
    ]
