# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-08 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20170613_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookface',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='bookface'),
            preserve_default=False,
        ),
    ]
