# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-09 03:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_auto_20170708_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mulu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u76ee\u5f55')),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='mulu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Mulu'),
        ),
    ]
