# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-09 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('dynastic', models.CharField(max_length=100)),
                ('wiki', models.TextField()),
            ],
        ),
    ]
