# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-12 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_auto_20170611_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='created_time',
            field=models.DateTimeField(null=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4'),
        ),
    ]
