# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-12 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fangji', '0003_auto_20170611_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fangji',
            name='prescription',
            field=models.TextField(verbose_name='\u65b9\u5242\u7ec4\u6210'),
        ),
    ]
