# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-12 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fangji', '0004_auto_20170612_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fangji',
            name='created_time',
            field=models.DateTimeField(null=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4'),
        ),
    ]
